#!/bin/sh

DIR=/usr/local/ppinger/

case "$1" in
start)
        cd $DIR/sbin/
        daemon -f -p /var/run/ppoller.pid ./ppoller.pl
        ;;
stop)
        kill -9 `cat /var/run/ppoller.pid`
        ;;
*)
        echo "Usage: `basename $0` {start|stop}" >&2
        exit 64
        ;;
esac

exit 0
