#! /bin/bash

### BEGIN INIT INFO
# Provides:          ppoller
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ppoller service
# Description:       Run ppoller service
### END INIT INFO

# PPinger installation directory
DIR=/opt/ppinger/

case "$1" in
  start)
    echo "Starting ppoller..."
    cd $DIR/bin/ && daemonize -l /var/run/ppoller.lock -p /var/run/ppoller.pid ./ppoller.pl
    ;;
  stop)
    echo "Stopping ppoller..."
    kill -9 `cat /var/run/ppoller.pid`
    sleep 2
    ;;
  *)
    echo "Usage: /etc/init.d/ppoller {start|stop}"
    exit 1
    ;;
esac

exit 0
