#!/bin/sh

DIR=/usr/local/ppinger/

case "$1" in
start)
        cd $DIR/sbin/
        nohup ./ppoller.pl > /dev/null 2>&1 & echo $! > /var/run/ppoller.pid
        ;;
stop)
        kill -9 `cat /var/run/ppoller.pid`
        ;;
*)
        echo "Usage: `basename $0` {start|stop}" >&2
        exit 64
        ;;
esac

exit 0
